extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
settings:
  react:
    version: detect
rules:
  '@typescript-eslint/ban-types':
    - error
    - types:
        '{}': false
  react/jsx-boolean-value:
    - error
    - always
